### ISSUE TITLE
Richardson-Lucy deconvolution in non-circulant mode fails

### ISSUE THREAD

**Issue by igorpisarev** [imagej/imagej-ops#586]
I am getting the following error when trying to run Richardson-Lucy deconvolution in non-circulant mode (using the latest version 0.43.1):
```
java.lang.IllegalArgumentException: No matching 'net.imagej.ops.deconvolve.NonCirculantNormalizationFactor/net.imagej.ops.special.inplace.UnaryInplaceOnlyOp' op

Request:
-	net.imagej.ops.deconvolve.NonCirculantNormalizationFactor/net.imagej.ops.special.inplace.UnaryInplaceOnlyOp(
		ArrayImg,
		ArrayImg,
		ArrayImg,
		ArrayImg,
		ArrayImg)

Candidates:
1. 	(RandomAccessibleInterval arg) =
	net.imagej.ops.deconvolve.NonCirculantNormalizationFactor(
		RandomAccessibleInterval arg,
		Dimensions k,
		Dimensions l,
		RandomAccessibleInterval fftInput,
		RandomAccessibleInterval fftKernel,
		Interval imgConvolutionInterval)
	Not enough arguments: 5 < 6

	at net.imagej.ops.DefaultOpMatchingService.singleMatch(DefaultOpMatchingService.java:432)
	at net.imagej.ops.DefaultOpMatchingService.findMatch(DefaultOpMatchingService.java:97)
	at net.imagej.ops.OpEnvironment.op(OpEnvironment.java:239)
	at net.imagej.ops.special.inplace.Inplaces.unary(Inplaces.java:110)
	at net.imagej.ops.deconvolve.RichardsonLucyF.createFilterComputer(RichardsonLucyF.java:148)
	at net.imagej.ops.filter.AbstractFFTFilterF.computeFilter(AbstractFFTFilterF.java:130)
	at net.imagej.ops.filter.AbstractFilterF.calculate(AbstractFilterF.java:186)
	at net.imagej.ops.filter.AbstractFilterF.calculate(AbstractFilterF.java:59)
	at net.imagej.ops.special.function.BinaryFunctionOp.run(BinaryFunctionOp.java:77)
	at net.imagej.ops.special.function.AbstractBinaryFunctionOp.run(AbstractBinaryFunctionOp.java:61)
	at org.scijava.command.CommandModule.run(CommandModule.java:199)
	at net.imagej.ops.OpEnvironment.run(OpEnvironment.java:950)
	at net.imagej.ops.OpEnvironment.run(OpEnvironment.java:157)
	at net.imagej.ops.deconvolve.DeconvolveNamespace.richardsonLucy(DeconvolveNamespace.java:190)
...
```

This is the code snippet I am using if that helps:
```
deconImg = opService.deconvolve().richardsonLucy(
	img, psf,
	null, null, null, null, null,
	10, true, false
);
```

**Comment by igorpisarev** [comment]
It seems that the bug was introduced between the releases 0.41.1 and 0.42.0.

**Comment by bnorthan** [comment]
@igorpisarev thanks for finding this, and thanks for the extra info regarding when it started it happening, that made it easy to track down what happened.  I messed up something when removing a redundant parameter, and will get this fixed this week.

**Comment by bnorthan** [comment]
Hi @igorpisarev see https://github.com/imagej/imagej-ops/pull/587. 

If no one reports any issues I'll merge this in a couple of days.

**Comment by igorpisarev** [comment]
Thanks @bnorthan, I tested your branch with the fix, and it works now!
