### ISSUE TITLE
Red error message when searching

### ISSUE THREAD

**Issue by haesleinhuepf** [imagej/imagej-ops#591]
Dear all,

I recently see more and more error messages popping up (red exceptions) in Fiji, when searching for something like "maximum" in the search field of the main window.  It might have something to do with Ops search as turning off the Ops search makes the error message going away.... Can anyone reproduce this?

Thanks!
Robert

[ERROR] Malfunctioning plugin: net.imagej.roi.RealMaskToRRAConverter
java.lang.ClassCastException: java.lang.Class cannot be cast to java.lang.reflect.ParameterizedType
	at net.imagej.roi.MaskConversionUtil.isBoolType(MaskConversionUtil.java:104)
	at net.imagej.roi.AbstractRealMaskToRRAConverter.canConvert(AbstractRealMaskToRRAConverter.java:63)
	at org.scijava.convert.AbstractConverter.canConvert(AbstractConverter.java:85)
	at org.scijava.convert.AbstractConverter.supports(AbstractConverter.java:144)
	at org.scijava.convert.AbstractConverter.supports(AbstractConverter.java:69)
	at org.scijava.plugin.HandlerService.getHandler(HandlerService.java:61)
	at org.scijava.plugin.HandlerService.supports(HandlerService.java:84)
	at org.scijava.convert.AbstractConvertService.supports(AbstractConvertService.java:92)
	at net.imagej.ops.search.OpSearchResult.lambda$typesMatch$0(OpSearchResult.java:148)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:174)
	at java.util.Spliterators$ArraySpliterator.tryAdvance(Spliterators.java:958)
	at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:126)
	at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:498)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:485)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:152)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:464)
	at net.imagej.ops.search.OpSearchResult.typesMatch(OpSearchResult.java:149)
	at net.imagej.ops.search.OpSearchResult.varFromType(OpSearchResult.java:142)
	at net.imagej.ops.search.OpSearchResult.buildShortSig(OpSearchResult.java:134)
	at net.imagej.ops.search.OpSearchResult.<init>(OpSearchResult.java:76)
	at net.imagej.ops.search.OpSearcher.lambda$search$2(OpSearcher.java:93)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.Iterator.forEachRemaining(Iterator.java:116)
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
	at net.imagej.ops.search.OpSearcher.search(OpSearcher.java:94)
	at org.scijava.search.DefaultSearchOperation$SearchAttempt.run(DefaultSearchOperation.java:174)
	at org.scijava.thread.DefaultThreadService$2.run(DefaultThreadService.java:221)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

**Comment by hinerm** [comment]
@ctrueden this seems to be an issue with Ops searching in general. I can't get any Ops search results right now:

![image](https://user-images.githubusercontent.com/1123809/95887736-d1481a00-0d45-11eb-8e6a-b1e6a793bf9b.png)
